config_name: "Dyode v2"
config_version : 1.0
config_date: 2017-07-25

modules:

    "Siemens PLC":
      type: s7
      ip: 127.0.0.1
      port_out: 102
      databases:
        1:
          - 0-20
          - 30-40
        2:
          - 0-10
